apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingest-ingress
  annotations:
    # specifically target NGINX ingress controller
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
spec:
  rules:
  {{- $defaultPath := .Values.ingress.ingest.defaultPath -}}
  {{- $defaultServicePort := .Values.ingress.ingest.defaultServicePort -}}
  {{ range .Values.ingress.ingest.hosts }}
  {{ $service := .service }}
    - host: {{ .hostname  }}
      http:
        paths:
          - path: {{ .path | default $defaultPath }}
            backend:
              serviceName: {{ $service }}
              servicePort: {{ .port | default $defaultServicePort }}
        {{ range .additionalRules }}        
          - path: {{ .path | default $defaultPath }}
            backend:
              serviceName: {{ $service }}
              servicePort: {{ .port | default $defaultServicePort }}
        {{ end }}
  {{ end }}
