aws:
  roleArn: default
  s3:
    bucket: ingest-backup
    directory: default
secret:
  aws:
    accessKey: default
    secretAccessKey: default
backup:
  image:
    repository: quay.io/humancellatlas/ingest-backup
    tag: 56c442d
    pullPolicy: Always
  cronSchedule: 0 0 * * *
verification:
  image:
    repository: quay.io/humancellatlas/ingest-backup-verify
    tag: 56c442d
    pullPolicy: Always
  cronSchedule: 30 0 * * *
  slack:
    webhookUrl: default
