aws:
  roleArn: default
  s3:
    bucket: ingest-backup
    directory: default
secret:
  aws:
    accessKey: default
    secretAccessKey: default
backup:
  image:
    repository: quay.io/humancellatlas/ingest-backup
    tag: 1bb4c6d
    pullPolicy: Always
  cronSchedule: 0 0 * * *
verification:
  image:
    repository: quay.io/humancellatlas/ingest-backup-verify
    tag: 1bb4c6d
    pullPolicy: Always
  mongo:
    image:
      repository: mongo
      tag: 3.4.3
      pullPolicy: Always
  cronSchedule: 30 0 * * *
  slack:
    webhookUrl: default
